alfabetizacao_medallion:
  target: offline
  outputs:
    offline:
      type: duckdb
      path: "{{ env_var('DBT_DUCKDB_PATH', ':memory:') }}"
      threads: 1
    cloud:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: alfabetizacao
      location: "{{ env_var('DBT_LOCATION') }}"
      threads: 4
      priority: interactive
      maximum_bytes_billed: "{{ env_var('DBT_MAXIMUM_BYTES_BILLED') | int }}"
